### ISSUE TITLE
Pre-Installer Script

### ISSUE THREAD

**Issue by nexusguy59** [cited/nagios-webmin-module#1]
After following the instructions I get what you see below:

cfadmin@ohnag02:/var/tmp$ sudo ./pre-install.sh 
./pre-install.sh: 9: ./pre-install.sh: Syntax error: "(" unexpected

How do we fix this?

Thanks,
Michael

**Comment by DavidGhedini** [comment]
Hi - I can't reproduce this.  Is the script executable?  
I've added an Ubuntu-only script that you can use as well:
https://github.com/cited/nagios-webmin-module/blob/master/scripts/ubuntu-preinstall.sh

**Comment by DavidGhedini** [comment]
Did this fix the issue @nexusguy59?

**Comment by nexusguy59** [comment]
> Hi - I can't reproduce this. Is the script executable?
> I've added an Ubuntu-only script that you can use as well:
> https://github.com/cited/nagios-webmin-module/blob/master/scripts/ubuntu-preinstall.sh

Thank you for your reply, I am sorry just now seeing this. Yes the script is executable, I will try it again in a day or two and report back to you. Thank you again for the response.

**Comment by nexusguy59** [comment]
> Did this fix the issue @nexusguy59?

Sorry David I am going to try it tonight or in the morning I will let ya know. 
Thanks,
Michael

**Comment by DavidGhedini** [comment]
Closed as no follow up.
