### ISSUE TITLE
Issues installing nrp plugin and service

### ISSUE THREAD

**Issue by MonsterITServices** [cited/nagios-webmin-module#2]
Hi We cant install the NRP service or plugin we get this issue.
How can we resolve this please?
`cd ./src/; make
make[1]: Entering directory '/tmp/nrpe-3.2.1/src'
gcc -g -O2 -I/usr/include/krb5 -DHAVE_CONFIG_H -I ../include -I ./../include -o nrpe ./nrpe.c ./utils.c ./acl.c -lssl -lcrypto -lnsl
./nrpe.c: In function 'init_ssl':
./nrpe.c:285:9: warning: 'ENGINE_load_builtin_engines' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
285 | ENGINE_load_builtin_engines();
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../include/common.h:36,
from ./nrpe.c:38:
/usr/include/openssl/engine.h:358:28: note: declared here
358 | OSSL_DEPRECATEDIN_3_0 void ENGINE_load_builtin_engines(void);
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./nrpe.c:286:9: warning: 'RAND_set_rand_engine' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
286 | RAND_set_rand_engine(NULL);
| ^~~~~~~~~~~~~~~~~~~~
In file included from ../include/common.h:35,
from ./nrpe.c:38:
/usr/include/openssl/rand.h:52:27: note: declared here
52 | OSSL_DEPRECATEDIN_3_0 int RAND_set_rand_engine(ENGINE *engine);
| ^~~~~~~~~~~~~~~~~~~~
./nrpe.c:287:9: warning: 'ENGINE_register_all_complete' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
287 | ENGINE_register_all_complete();
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../include/common.h:36,
from ./nrpe.c:38:
/usr/include/openssl/engine.h:415:27: note: declared here
415 | OSSL_DEPRECATEDIN_3_0 int ENGINE_register_all_complete(void);
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./nrpe.c:432:25: warning: 'ERR_get_error_line_data' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
432 | while ((x = ERR_get_error_line_data(NULL, NULL, NULL, NULL)) != 0) {
| ^~~~~
In file included from ../include/common.h:34,
from ./nrpe.c:38:
/usr/include/openssl/err.h:413:15: note: declared here
413 | unsigned long ERR_get_error_line_data(const char **file, int *line,
| ^~~~~~~~~~~~~~~~~~~~~~~
./nrpe.c:456:22: warning: implicit declaration of function 'get_dh2048' [-Wimplicit-function-declaration]
456 | dh = get_dh2048();
| ^~~~~~~~~~
./nrpe.c:456:20: warning: assignment to 'DH *' {aka 'struct dh_st *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
456 | dh = get_dh2048();
| ^
./nrpe.c:458:17: warning: 'DH_free' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
458 | DH_free(dh);
| ^~~~~~~
In file included from /usr/include/openssl/dsa.h:51,
from /usr/include/openssl/x509.h:37,
from /usr/include/openssl/ssl.h:31,
from ../include/common.h:32,
from ./nrpe.c:38:
/usr/include/openssl/dh.h:200:28: note: declared here
200 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
| ^~~~~~~
./nrpe.c: In function 'handle_conn_ssl':
./nrpe.c:1930:25: warning: 'ERR_get_error_line_data' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
1930 | while ((x = ERR_get_error_line_data(NULL, NULL, NULL, NULL)) != 0) {
| ^~~~~
In file included from ../include/common.h:34,
from ./nrpe.c:38:
/usr/include/openssl/err.h:413:15: note: declared here
413 | unsigned long ERR_get_error_line_data(const char **file, int *line,
| ^~~~~~~~~~~~~~~~~~~~~~~
./nrpe.c: In function 'read_config_dir':
./nrpe.c:1064:68: warning: '%s' directive output may be truncated writing up to 255 bytes into a region of size 254 [-Wformat-truncation=]
1064 | snprintf(config_file, sizeof(config_file) - 1, "%s/%s", dirname, dirfile->d_name);
| ^~
In file included from /usr/include/stdio.h:894,
from ../include/config.h:31,
from ./nrpe.c:37:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:10: note: '__builtin___snprintf_chk' output 2 or more bytes (assuming 257) into a destination of size 255
71 | return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
72 | __glibc_objsize (__s), __fmt,
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
73 | __va_arg_pack ());
| ~~~~~~~~~~~~~~~~~
./acl.c: In function 'is_an_allowed_host':
./acl.c:569:46: warning: '__builtin_memcmp_eq' specified bound 16 exceeds source size 8 [-Wstringop-overread]
569 | if (!memcmp(&addr6.sin6_addr, &host, sizeof(addr6.sin6_addr)))
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./acl.c:494:42: note: source object declared here
494 | int is_an_allowed_host(int family, void *host)
| ~~~~~~^~~~
/bin/ld: /tmp/ccZTVHR6.o: in function `init_ssl':
/tmp/nrpe-3.2.1/src/./nrpe.c:456: undefined reference to `get_dh2048'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:48: nrpe] Error 1
make[1]: Leaving directory '/tmp/nrpe-3.2.1/src'
make: *** [Makefile:77: nrpe] Error 2`

**Comment by DavidGhedini** [comment]
What OS is this?

**Comment by DavidGhedini** [comment]
Closing as no response
